// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA--AHbxwMAqfS_vtYF_pyHslDoS_UL-CU',
    appId: '1:190488372691:web:d280b4093f9ee0f3ab3b26',
    messagingSenderId: '190488372691',
    projectId: 'gamifit69420',
    authDomain: 'gamifit69420.firebaseapp.com',
    storageBucket: 'gamifit69420.appspot.com',
    measurementId: 'G-CL686PFE45',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVrba4USFkfV77_01ARCQEJ4nctQ6KNkk',
    appId: '1:190488372691:android:e2d0274fdaab6f0eab3b26',
    messagingSenderId: '190488372691',
    projectId: 'gamifit69420',
    storageBucket: 'gamifit69420.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqChJRPNQmjNjoVFauSilajgkbcosHGCQ',
    appId: '1:190488372691:ios:56764de7a5671768ab3b26',
    messagingSenderId: '190488372691',
    projectId: 'gamifit69420',
    storageBucket: 'gamifit69420.appspot.com',
    iosBundleId: 'com.example.flutterapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqChJRPNQmjNjoVFauSilajgkbcosHGCQ',
    appId: '1:190488372691:ios:fab97bd7d7d7ad02ab3b26',
    messagingSenderId: '190488372691',
    projectId: 'gamifit69420',
    storageBucket: 'gamifit69420.appspot.com',
    iosBundleId: 'com.example.flutterapp.RunnerTests',
  );
}
